fix(testing+linting): add nox lint+format directives
googleapis/langchain-google-spanner-python pull request #123
Opened 2024-12-26 11:05 UTC by odeke-em

This change introduces new nox directives:
* blacken: `nox -s blacken`
* format: `nox -s format` to apply formatting to files
* lint: `nox -s lint` to flag linting issues
* unit: to run unit tests locally

which are the basis to enable scalable development and continuous testing as I prepare to bring in
Approximate Nearest Neighors (ANN) functionality into this package.

Also while here, fixed a typo in the README.rst file that didn't have the correct import path.

2024-12-27 04:30 UTC, gauravpurohit06 approved these changes

2024-12-27 04:31 UTC, gauravpurohit06 commented
@Yuan325, Can you also review it  and run the tests?

2025-01-08 00:24 UTC, averikitsch requested changes

2025-01-08 00:24 UTC, averikitsch commented on noxfile.py
Please remove these changes. This project (and consistently across other projects) does not use nox to run lints. Please see https://github.com/googleapis/langchain-google-spanner-python/blob/main/.github/workflows/lint.yml

2025-01-10 07:45 UTC, gauravpurohit06 commented on noxfile.py
Hi @averikitsch, Do we have a reason for not using it?

2025-01-14 17:54 UTC, averikitsch commented on noxfile.py
* The dependencies are in the pyproject.toml that get updated by dependabot. This file does not get automatically updated
* This config is copied from repos that use a different package naming schema, different directory structure, and setup.py

Also, for the future we should not be using "fix" in the commit message, that will trigger a new release and we do not create new releases for CI updates.

2025-01-14 17:55 UTC, averikitsch commented on README.rst
> +    from langchain_google_spanner import SpannerVectorstore
Please make sure you keep your PRs scoped to 1 change at a time.

2025-01-14 18:29 UTC, odeke-em commented on noxfile.py
@averikitsch thanks for your reply. The purpose of the PR is to get functionality to allow code to be formatted, unit tests to be run locally et al as code is being built by developers so as to speed up development. Do you perhaps have alternative suggestions for how to accomplish the above?

2025-01-15 09:31 UTC, odeke-em commented on noxfile.py
>Please remove these changes. This project (and consistently across other projects) does not use nox to run lints.

@averikitsch python-spanner the main repo representing Cloud Spanner does use nox https://github.com/googleapis/python-spanner/blob/main/noxfile.py  for linting, testing and all, for more than 7 years https://github.com/googleapis/python-spanner/commits/main/noxfile.py?after=32e761b0d4052938bf67cfec63a0e83702a35ada+34.

Could you perhaps explain your objections and help out with suggestions? This PR has been sitting for more than 2 weeks and it moving is necessary to accomplish other tasks.

2025-01-16 06:14 UTC, gauravpurohit06 commented on noxfile.py
Hi @averikitsch, 

@odeke-em  is trying to define a `nox task` for liniting and running the test locally and for linting he is using `black` (i.e. we are using same in our [workflows](https://github.com/googleapis/langchain-google-spanner-python/blob/main/.github/workflows/lint.yml)). I don't see any problem with it as not changing any dependencies.  

If `noxfile.py` is not getting copied from any other repos or configurations.. I don't see any problem with the change.

2025-01-16 21:53 UTC, averikitsch commented on noxfile.py
This will be diverting from the other langchain repos. I am fine with adding it, but the Spanner team will have to keep it up to date as I mentioned that it doesn't get auto-updates and will not stay in sync with the repo CI setup. This may cause long term confusion for maintainers.

2025-01-16 21:58 UTC, averikitsch submitted a review, later dismissed

2025-01-16 21:58 UTC, averikitsch commented on noxfile.py
> +ISORT_VERSION = "isort==5.11.0"
Use versions listed in the pyproject.toml

2025-01-16 21:58 UTC, averikitsch commented on noxfile.py
> +    session.run("python", "setup.py", "check", "--restructuredtext", "--strict")
We don't have a setup.py

2025-01-16 21:58 UTC, averikitsch commented on noxfile.py
> +        os.path.join("tests", "unit"),
We don't have a unit directory

2025-01-16 21:58 UTC, averikitsch commented
Please fix the lint errors

2025-01-16 21:58 UTC, averikitsch commented
/gcbrun

2025-01-16 22:00 UTC, averikitsch commented
Please work with @gauravpurohit06 to run the tests via the comment "/gcbrun"

2025-01-20 06:01 UTC, odeke-em commented on noxfile.py
> +        os.path.join("tests", "unit"),
@averikitsch in the follow-up PR I added one, but didn't want to introduce it in this already huge PR.

2025-01-20 06:31 UTC, odeke-em commented on noxfile.py
Thank you @averikitsch. It won't need many updates except indeed as you mention mirror-ing pyproject dependencies into setup.py and those won't be updates needed even with a year. However, the benefits of having non-Googlers be able to develop and make updates robustly I believe shall heavily outweigh any of those. Also currently I can't even look at the Kokoro statuses as one needs to be a Googler per https://console.cloud.google.com/cloud-build/triggers/edit/16ba25ff-d74a-42ef-8f19-9780571439ab?project=585680705374
<img width="1067" alt="Screenshot 2025-01-19 at 10 15 12 PM" src="https://github.com/user-attachments/assets/d1744d47-1764-44f1-9137-957db8a3b0fd" />

2025-01-20 06:34 UTC, odeke-em commented on README.rst
> +    from langchain_google_spanner import SpannerVectorstore
Alright, reverted.

2025-01-22 11:00 UTC, gauravpurohit06 commented
/gcbrun

2025-01-22 11:04 UTC, gauravpurohit06 commented
Please fix the linting errors.

2025-01-24 01:55 UTC, odeke-em commented
/gcbrun

2025-01-24 02:07 UTC, odeke-em commented
@gauravpurohit06 kindly help me run /gcbrun

2025-01-24 04:20 UTC, gauravpurohit06 commented
/gcbrun

2025-01-24 22:46 UTC, averikitsch commented on noxfile.py
* The test dependencies get updated more than yearly via automation. Therefore will be out of sync of the CI system that is getting periodic updates which may cause confusion. 
* This Python library does not use setup.py, it uses a pyproject.toml (https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#modernize-setup-py-project).
* I am unsure how this relates to permissions for accessing CI tests. You can run the tests locally using `pytest` as noted in https://github.com/googleapis/langchain-google-spanner-python/blob/main/DEVELOPER.md#testing. Using the noxfile is just wrapping that command.

2025-01-24 22:52 UTC, averikitsch commented on noxfile.py
> +ISORT_VERSION = "isort==5.13.2"
Instead of setting these can you just install the test dependencies from pyproject.toml like `pip install .[test]`?

2025-01-27 18:22 UTC, odeke-em commented on noxfile.py
> +ISORT_VERSION = "isort==5.13.2"
Thanks for showing me this, I've fixed it. Done!

2025-01-27 19:25 UTC, gauravpurohit06 commented
/gcbrun

2025-01-28 03:34 UTC, odeke-em commented
@gauravpurohit06 kindly help with /gcbrun

2025-01-30 08:06 UTC, gauravpurohit06 commented
/gcbrun

2025-01-30 08:41 UTC, odeke-em commented
@gauravpurohit06 kindly please help with /gcbrun

2025-01-30 09:27 UTC, gauravpurohit06 commented
/gcbrun

2025-01-30 10:35 UTC, merged