Ann support update distance strategies
googleapis/langchain-google-spanner-python pull request #124
Opened 2024-12-26 12:40 UTC by odeke-em

feat: add Approximate Nearest Neighbor support to distance strategies
    
This change adds ANN distance strategies for GoogleSQL semantics.
While here started unit tests to effectively test out components
without having to have a running Cloud Spanner instance.
    
Updates #94

2025-01-20 10:56 UTC, gauravpurohit06 requested changes
I have added the granular comments. Please run the lints add line breaks to improve the readability.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        strategy: DistanceStrategy = DistanceStrategy.COSINE,
you actually don't need it here. The distance to use actually get fixed when you initialize the `SpannerVectorStore` class.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +    def search_by_ANN(
Please make this function private.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +    def search_by_ANN(
You need to align your functions with [VectorStore](https://api.python.langchain.com/en/latest/vectorstores/langchain_core.vectorstores.VectorStore.html) interface defined in langchain. 

Based on the `QueryParameters.NearestNeighborsAlgorithm` which user is passing at the time of initialization of this class `not init_vector_store_table`, we should decide whether we want to use the KNN/ANN.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        where_condition: str = None,
Use `pre_filter` and `post_filter` terminology.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        index_name: str,
You don't need to take it from the user... as it's defined in SpannerVectorStore at the time of initialization.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        embedding_column_name: str,
You don't need to take it from the user... as it's defined in SpannerVectorStore at the time of initialization.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        strategy: DistanceStrategy = DistanceStrategy.COSINE,
You don't need to take it from the user... as it's defined in SpannerVectorStore at the time of initialization.

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        limit: int = None,
rename it to `k`

2025-01-20 10:56 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        limit: int = None,
rename it to `K`

2025-01-21 09:54 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +DISTANCE_STRATEGY_STRING = {
Done, thanks!

2025-01-21 10:05 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        limit: int = None,
Won't the K be quite confusing given that that's used inside kNN while this is ANN?

2025-01-21 10:06 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        strategy: DistanceStrategy = DistanceStrategy.COSINE,
This method though isn't exposed to the user, which is why I preceded it with `_` as `_query_ANN` as I need to test it out individually.

2025-01-22 10:52 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    num_leaves: Optional[int] = None  # Only necessary for ANN
Done

2025-01-27 06:22 UTC, gauravpurohit06 requested changes
Added two more comments, based on it... you also need to update function signature throughout the file not mentioning it explicitly.

2025-01-27 06:22 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +class VectorSearchIndex:
We can create this class as derived class of `SecondaryIndex` and inherit the `SecondaryIndex`

2025-01-27 06:22 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +    columns: list[str]  # Each column passed in must have ARRAY<FLOAT64> type.
If we use inheritance, we can remove it.

2025-01-28 11:56 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    num_leaves: Optional[int] = None  # Only necessary for ANN
@gauravpurohit06 sadly the use of dataclass and trying to inherit from it creates a leaky abstraction that takes much more time to use than if we had simply created a class resulting in
```shell
TypeError: non-default argument 'num_leaves' follows default argument
```

It is so much simpler to use basic classes and then usual inheritance otherwise inheritance of dataclass doesn't work at all.

2025-01-28 11:56 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    num_branches: Optional[int] = None  # Only necessary for ANN
Done, thanks!

2025-01-28 11:56 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    tree_depth: Optional[int] = None  # Only necessary for ANN
Done, thanks!

2025-01-30 11:47 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +_GOOGLE_DISTANCE_ALGO_NAMES = {
I gave it a more appropriate name, thanks!

2025-01-30 11:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +_PG_DISTANCE_ALGO_NAMES = {
Ditto, thank you!

2025-01-30 11:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +class AlgoKind(Enum):
Done, thanks!

2025-01-30 11:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        if kind == AlgoKind.ANN:
Done, thanks!

2025-01-30 11:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +            ddl_statements += SpannerVectorStore._generate_secondary_indices_ddl_KNN(
Done, thanks!

2025-01-30 12:46 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    index_type: Optional[DistanceStrategy] = None  # Only necessary for ANN
I updated it to `distance_type` as `index_*` as a prefix is redundant given that it is already for a VectorSearchIndex.

2025-01-30 12:47 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> -                if secondary_index.storing_columns is None:
It is only for *_KNN

2025-01-30 12:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        limit=None,
It is a must for ANN queries, they'll fail without it.

2025-01-30 12:48 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +                f"ANN is only supported for the GoogleSQL dialect not {dialect}"
Done.

2025-01-31 07:46 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    def search_by_ANN(
Indeed. Done.

2025-01-31 07:52 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        strategy: DistanceStrategy = DistanceStrategy.COSINE,
Yeah that is on a static method that's isolated and used for testing.

2025-01-31 07:53 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    def search_by_ANN(
Yup, I did.

2025-01-31 07:53 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +            ddl_statements += SpannerVectorStore._generate_secondary_indices_ddl_ANN(
Yes indeed, I already did.

2025-01-31 07:53 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +DEFAULT_ANN_TREE_DEPTH = 2
Done.

2025-02-03 08:11 UTC, gauravpurohit06 requested changes
@odeke-em, Other than granular comments there are inconsistencies in return type here through the implementation and also use of `None` keyword. Please correct it.

2025-02-03 08:11 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +                embedding_column_is_nullable=kwargs.get("embedding_column_is_nullable", False),
We don't have to get it from customer. We can get it from the schema or I think we always have to use `Not NULL` constraint when making a query.

2025-02-03 08:11 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +    def add_ann_rows(
what is the use of this method? Adding data is independent of ann/knn.

2025-02-03 08:11 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +                pre_filter=kwargs.get("pre_filter", ""),
You can also define it as Optional Parameter in the function signature... so that customer knows these parameters are available.

2025-02-03 08:11 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        if not self._skip_not_nullable_columns:
We can do this validate without customer explicitly asking for it, if a column has a not null constraint and is it's not part of `_columns_to_insert ` then we should raise the exception. No matter what's the value of `_skip_not_nullable_columns `

2025-02-03 09:20 UTC, gauravpurohit06 commented
/gcbrun

2025-02-03 09:54 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        limit: int = None,
Done, thanks!

2025-02-03 11:17 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        embedding_column_name: str,
That is on a static method which is being explicitly invoked in tests and when used in the instance method we derive the name from what was already set.

2025-02-03 11:17 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +            embedding or self._embedding_service,
Done, thank you!

2025-02-03 11:18 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +                embedding_column_is_nullable=kwargs.get("embedding_column_is_nullable", False),
We could get it from the schema def but I can do that in a follow up PR after this one lands.

2025-02-03 11:19 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +                pre_filter=kwargs.get("pre_filter", ""),
It was defined in the signature for similary_search_by_vector.

2025-02-03 11:20 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        if not self._skip_not_nullable_columns:
I've removed it and I'll keep iterating in a later PR.

2025-02-03 11:20 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        is_embedding_nullable: bool = False,
Removed, thanks!

2025-02-03 11:20 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +                pre_filter=kwargs.get("pre_filter", ""),
Done.

2025-02-03 13:25 UTC, gauravpurohit06 requested changes
in public apis... decide whether to use knn vs ann... Mention it explicitly what to do.

2025-02-03 13:25 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +    def __using_ANN(self):
You also need to use this function in `max_marginal_relevance_search_with_score_by_vector` and `similarity_search_with_score_by_vector` and not go directly to KNN.

2025-02-03 13:25 UTC, gauravpurohit06 commented on src/langchain_google_spanner/vector_store.py
> +        if self.__using_ANN:
Please remove it from here  as you will already this check in `max_marginal_relevance_search_with_score_by_vector` and `similarity_search_with_score_by_vector`

2025-02-03 13:41 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +    def __using_ANN(self):
@gauravpurohit06 I plan on doing that in a follow up PR. This one is already massive as it is and has taken 4+ weeks.

2025-02-03 13:42 UTC, odeke-em commented on src/langchain_google_spanner/vector_store.py
> +        if self.__using_ANN:
@gauravpurohit06 could we please do that in a follow up PR? I plan on mailing it, just that this one has become too huge

2025-02-03 14:50 UTC, odeke-em commented
@gauravpurohit06 I humbly and highly recommend that we get this PR in as is, then I can send more given firstly how massive it is, I actually had to delete code out of other helpers to keep in manageable, plus your time constraint. Getting 90% in before you are out of the office goes a much longer way than our 5+ week long PR. Sending smaller PRs for the other parts is planned as I mentioned a couple of times offline and allows for much more effective testing too.

2025-02-04 06:12 UTC, gauravpurohit06 commented
/gcbrun

2025-02-04 09:38 UTC, odeke-em commented
@gauravpurohit06 kindly help me run gcbrun.

2025-02-04 09:54 UTC, gauravpurohit06 commented
/gcbrun

2025-02-04 10:59 UTC, gauravpurohit06 approved these changes
LGTM

2025-02-04 10:59 UTC, merged